name: t2t1
description: A new Flutter project.
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '>=3.1.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter


  syncfusion_flutter_charts: ^19.4.56  # Updated version

  cupertino_icons: ^1.0.2

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^2.0.0
  flutter_inappwebview: ^5.3.2
  url_launcher: ^6.2.4
  flutter_otp_text_field: ^1.1.0+2
  fl_chart: ^0.65.0
  carousel_slider: ^4.0.0
  charts_flutter: ^0.12.0
  youtube_player_flutter: ^8.1.2
  expand_widget: ^2.1.0
  table_calendar: ^3.0.0
  http: ^0.13.3  # existing dependency
  provider: ^5.0.0
  shared_preferences: ^2.0.8


flutter:
  uses-material-design: true
